name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better diff context

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI Review
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Optional: Add your model-specific API key
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          # MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          # HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
          GITHUB_EVENT_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python src/review_pr.py --verbose