name: AI PR Review

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better diff context

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI Review
        env:
          # Use the default GITHUB_TOKEN provided by GitHub Actions
          # This token automatically inherits the job's permissions
          GITHUB_TOKEN: ${{ github.token }}
          # Add the required API key based on your config.yaml provider
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # Other API keys if needed
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          # MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          # HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
          GITHUB_EVENT_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          # Set the Python path to include the current directory
          PYTHONPATH: ${{ github.workspace }}
        run: |
          # Show current directory structure for debugging
          find . -type f -name "*.py" | sort
          
          # Run the review script
          python src/review_pr.py --verbose